before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2 libpango1.0-0 libpangocairo-1.0.0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
  - wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb
  - sudo apt-get -y autoremove libtidy-0.99-0
  - sudo dpkg -i tidy-5.4.0-64bit.deb
language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
script:
  - pycodestyle
  - pydocstyle
  - pylint *.py
  - python build.py && git diff --no-ext-diff --exit-code
  - tidy -config .tidyrc -errors docs/*.html
  - piprot
