---
title: Craig Anderson
description:
    Personal site of Craig Anderson, a freelance product developer specialising in Python and Django based in London, England.
    Fan of music and craft beer.
    Not a sportsperson or an actor.
email: craiga@craiga.id.au
url: https://www.craiga.id.au
lang: en_AU
logo: /assets/avatar-400.optimised.jpg

author:
  name: Craig Anderson
  twitter: _craiga

twitter:
  username: _craiga

facebook:
  publisher: https://facebook.com/craiga

seo:
  type: Person
  name: Craig Anderson

collections:
  talks:
    output: true
    permalink: /:collection/:name
  lists:
    output: true
    permalink: /:collection/:name
  colours:
    output: true
    permalink: /:collection/:name

social:
  name: Craig Anderson
  links:
    - https://www.linkedin.com/in/craigeanderson
    - https://github.com/craiga
    - https://facebook.com/craiga
    - https://www.instagram.com/_craiga/
    - https://twitter.com/_craiga
    - https://www.last.fm/user/craiganderson
    - https://itunes.apple.com/profile/craigeanderson
    - https://bandcamp.com/craiga
    - https://soundcloud.com/craiga
    - https://www.discogs.com/user/craiga
    - https://www.songkick.com/users/craigeanderson
    - https://untappd.com/user/craiganderson
    - https://distiller.com/profile/craiga
    - https://www.nextfree.co.uk/for/craig-anderson
    - https://uk.yunojuno.com/p/craiga
    - https://bitbucket.org/craiganderson/
    - https://stackoverflow.com/users/1852024/craig-anderson
    - https://www.amazon.co.uk/gp/profile/amzn1.account.AGZM2LSRQUXGVNRQS4Y34TEUAHYQ
    - https://www.goodreads.com/craiga
    - https://www.meetup.com/members/24626782/
    - https://www.pinterest.co.uk/craiga/
    - https://www.reddit.com/user/craiga/
    - http://steamcommunity.com/id/craiga
    - http://blog.craiga.id.au/
    - https://www.strava.com/athletes/craiganderson
    - https://www.kiva.org/lender/craiga
    - https://hub.docker.com/u/craiga/
    - https://vimeo.com/craiga
    - https://keybase.io/craiganderson
    - https://www.quora.com/profile/Craig-Anderson-2
    - https://www.gog.com/u/craigeanderson
    - https://angel.co/craiganderson
    - https://www.twitch.tv/craigea


external_profiles:
  - url: https://www.linkedin.com/in/craigeanderson
    text: LinkedIn
    fontawesome_file: brands/linkedin
    fathom_goal_id: RZMNTD4P
  - url: https://facebook.com/craiga
    text: Facebook
    fontawesome_file: brands/facebook
    fathom_goal_id: IENTKMNL
  - url: https://www.instagram.com/_craiga/
    text: Instagram
    fontawesome_file: brands/instagram
    fathom_goal_id: FADRO2KF
  - url: https://twitter.com/_craiga
    text: Twitter
    fontawesome_file: brands/twitter
    fathom_goal_id: SH5PXDAV
  - url: https://www.last.fm/user/craiganderson
    text: Last.fm
    fontawesome_file: brands/lastfm
    fathom_goal_id: JSDRLIAD
  - url: https://itunes.apple.com/profile/craigeanderson
    text: Apple Music
    fontawesome_file: brands/apple
    fathom_goal_id: GDKIUVHW
  - url: https://bandcamp.com/craiga
    text: Bandcamp
    fontawesome_file: brands/bandcamp
    fathom_goal_id: X2FQORRC
  - url: https://soundcloud.com/craiga
    text: SoundCloud
    fontawesome_file: brands/soundcloud
    fathom_goal_id: GAT1FT3V
  - url: https://open.spotify.com/user/1231146638
    text: Spotify
    fontawesome_file: brands/spotify
    fathom_goal_id: XAPKNYOE
  - url: https://www.discogs.com/user/craiga
    text: Discogs
    fontawesome_file: solid/compact-disc
    fathom_goal_id: AJYZCT9Z
  - url: https://www.songkick.com/users/craigeanderson
    text: Songkick
    fontawesome_file: solid/volume-up
    fathom_goal_id: QM7TMDQA
  - url: https://untappd.com/user/craiganderson
    text: Untappd
    fontawesome_file: brands/untappd
    fathom_goal_id: B1NAWT7K
  - url: https://distiller.com/profile/craiga
    text: Distiller
    fontawesome_file: solid/wine-glass-alt
    fathom_goal_id: D8FODB5S
  - url: https://craiganderson.yelp.co.uk
    text: Yelp
    fontawesome_file: brands/yelp
    fathom_goal_id: M9ZSRPRO
  - url: https://www.nextfree.co.uk/for/craig-anderson
    text: Nextfree
    fontawesome_file: solid/calendar
    fathom_goal_id: XWPBRFFL
  - url: https://uk.yunojuno.com/p/craiga
    text: YunoJuno
    fontawesome_file: solid/asterisk
    fathom_goal_id: HBWA4CQY
  - url: https://angel.co/craiganderson
    text: AngelList
    fontawesome_file: brands/angellist
    fathom_goal_id: XIJAFZI7
  - url: https://use.worksome.co.uk/profile/28594
    text: Worksome
    fontawesome_file: solid/briefcase
    fathom_goal_id: EQ2E9DOK
  - url: https://djangogigs.com/developers/craig-anderson2/
    text: Djangogigs
    fontawesome_file: solid/handshake
    fathom_goal_id: JWKJFKGH
  - url: https://snap.hr/u/33ba0389-fdfb-4fca-8f37-6ac81bc7630a/
    text: Snap.hr
    fontawesome_file: solid/briefcase
    fathom_goal_id: AFQMRRD3
  - url: https://github.com/craiga
    text: GitHub
    fontawesome_file: brands/github
    fathom_goal_id: LYIBX1EV
  - url: https://bitbucket.org/craiganderson/
    text: Bitbucket
    fontawesome_file: brands/bitbucket
    fathom_goal_id: UYEMOYIC
  - url: https://gitlab.com/craiganderson
    text: GitLab
    fontawesome_file: brands/gitlab
    fathom_goal_id: QYDMXJMS
  - url: https://pypi.org/user/craiga/
    text: PyPI
    fontawesome_file: brands/python
    fathom_goal_id: WCMSPHM9
  - url: https://stackoverflow.com/users/1852024/craig-anderson
    text: Stack Overflow
    fontawesome_file: brands/stack-overflow
    fathom_goal_id: FLGYEF4N
  - url: https://www.codewars.com/users/craiga
    text: Codewars
    fontawesome_file: solid/terminal
  - url: https://www.udemy.com/user/craig-anderson-27/
    text: Udemy
    fontawesome_file: solid/graduation-cap
  - url: https://www.etsy.com/uk/people/craiganderson
    text: Etsy
    fontawesome_file: brands/etsy
  - url: https://www.kickstarter.com/profile/craiga
    text: Kickstarter
    fontawesome_file: brands/kickstarter
  - url: https://ko-fi.com/craiga
    text: Ko-fi
    fontawesome_file: solid/mug-hot
  - url: https://www.amazon.co.uk/gp/profile/amzn1.account.AGZM2LSRQUXGVNRQS4Y34TEUAHYQ
    text: Amazon
    fontawesome_file: brands/amazon
  - url: https://www.goodreads.com/craiga
    text: Goodreads
    fontawesome_file: brands/goodreads
  - url: https://medium.com/@_craiga
    text: Medium
    fontawesome_file: brands/medium
  - url: https://www.meetup.com/members/24626782/
    text: Meetup
    fontawesome_file: brands/meetup
  - url: https://www.pinterest.co.uk/craiga/
    text: Pinterest
    fontawesome_file: brands/pinterest
  - url: https://www.reddit.com/user/craiga/
    text: Reddit
    fontawesome_file: brands/reddit
  - url: https://www.producthunt.com/@craiga
    text: Product Hunt
    fontawesome_file: brands/product-hunt
  - url: https://unsplash.com/@craiganderson
    text: Unsplash
    fontawesome_file: solid/camera
  - url: http://steamcommunity.com/id/craiga
    text: Steam
    fontawesome_file: brands/steam
  - text: SW-0552-7913-6509
    fontawesome_file: brands/nintendo-switch
  - url: https://account.xbox.com/en-us/profile?gamertag=craigea
    text: Xbox
    fontawesome_file: brands/xbox
  - url: https://www.gog.com/u/craigeanderson
    text: GOG
    fontawesome_file: solid/gamepad
  - url: https://vgcollect.com/craiga
    text: VGCollect
    fontawesome_file: solid/gamepad
  - url: https://www.twitch.tv/craigea
    text: Twitch
    fontawesome_file: brands/twitch
  - url: http://blog.craiga.id.au/
    text: Tumblr
    fontawesome_file: brands/tumblr
  - url: https://curiouscat.me/craiga
    text: Curious Cat
    fontawesome_file: solid/cat
  - url: https://www.strava.com/athletes/craiganderson
    text: Strava
    fontawesome_file: brands/strava
  - url: https://www.kiva.org/lender/craiga
    text: Kiva
    fontawesome_file: solid/leaf
  - url: https://hub.docker.com/u/craiga/
    text: Docker Hub
    fontawesome_file: brands/docker
  - url: https://vimeo.com/craiga
    text: Vimeo
    fontawesome_file: brands/vimeo
  - url: https://keybase.io/craiganderson
    text: Keybase
    fontawesome_file: brands/keybase
  - url: https://www.quora.com/profile/Craig-Anderson-2
    text: Quora
    fontawesome_file: brands/quora
  - url: https://trello.com/craigea
    text: Trello
    fontawesome_file: brands/trello
  - url: https://www.patreon.com/craiga
    text: Patreon
    fontawesome_file: brands/patreon
  - url: https://www.paypal.me/craigeanderson
    text: PayPal
    fontawesome_file: brands/paypal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: '**/plugin/**'
    values:
      sitemap: false

permalink: /:categories/:year/:month/:day/:title
